### PR TITLE
JSON template

### PR DESCRIPTION
**Pull request by martonpe**

### CODE REVIEW

**Comment by tmichel** [comment]
Do we want to blur the line between the log that is produced by the application and logspout log? 

Otherwise LGMT.

**Comment by rgabo** [comment]
@tmichel what's our alternative?

**Comment by tmichel** [comment]
@rgabo the only alternative I can think of is that we treat it as a string basically a foreign body in the log. But that doesn't seem too good. So let's roll with the unified JSON approach.

**Comment by tmichel** [comment]
@martonpe I cannot merge the PR, so merge at will. :smile:

**Comment by rgabo** [comment]
@tmichel try now

**Pull request merged**
